import math
value = 4.35
print(math.floor(value))
print(math.ceil(value))
print(round(value))
print(round(4.5))
print(round(5.5))
print(math.pi)
print(math.e)
print(math.inf)
print(math.nan)
print(math.log(math.e))
print(math.sin(10))
print(math.degrees(math.pi/2))
print(math.radians(180))
import random
print(random.seed(42))
print(random.randint(0,100))
mylist = list(range(0,20))
print(mylist)
print(random.choice(mylist))
print(random.choices(population=mylist,k=10))
print(random.sample(population=mylist,k=10))
random.shuffle(mylist)
print(mylist)
print(random.uniform(a=0,b=100))
print(random.gauss(mu=0,sigma=1))